mongo_host : penny.infocura.lan
gecko_bin : /usr/bin/gd
gecko_log : /var/log/cte/the_harvest
log_path : /var/log/cte/the_harvest/
log_level : INFO
log_format : "%(asctime)s - %(levelname)s: %(message)s"
log_date_format : "%H:%M:%S"
